import { StyleSheet, Text, View, Image } from "react-native";
import React from "react";
import KanyeImg from "../assets/KanyeCoverArt.jpg";
import { Ionicons } from "@expo/vector-icons";

const HorizontalProfileInfoComp = () => {
  return (
    <View style={styles.wrapper}>
      <View style={styles.profileImgView}>
        <Image style={styles.profileImgeStyling} source={KanyeImg} />
      </View>
      <View style={styles.textsWrapperView}>
        <View style={styles.channelNameAndUsername}>
          <Text style={styles.channelName}>Eric Bidopa</Text>
          <Text style={styles.smallTexts}>@KanyeWest</Text>
        </View>
        <View>
          <Text style={styles.smallTexts}>10M Subscribers</Text>
        </View>
        <View>
          <Text
            style={styles.smallTexts}
            numberOfLines={3}
            ellipsizeMode="tail"
          >
            Provided to YouTube by Vydia Revelations 19:1 · Choi Jesus More ℗
            2019 INC Released on: 2019-12-25 Composer More: Sunday Service Choir
            Auto-generated by
          </Text>
        </View>
      </View>
      <View style={styles.menuWrapperView}>
        <Ionicons name="options" size={25} color="black" />
      </View>
    </View>
  );
};

export default HorizontalProfileInfoComp;

const styles = StyleSheet.create({
  wrapper: {
    flexDirection: "row",
    backgroundColor: "yellow",
    width: "100%",
    height: 130, // Set a specific height for the item
    marginBottom: 10,
  },
  profileImgView: {
    backgroundColor: "lightblue",
    width: 66, // Set the size of the image wrapper
    height: 66, // Set the size of the image wrapper
    overflow: "hidden",
  },
  profileImgeStyling: {
    width: "100%",
    height: "100%",
    borderRadius: 33,
  },

  textsWrapperView: {
    backgroundColor: "orange",
    flex: 1,
    paddingLeft: 10,
    justifyContent: "space-between",
    flexDirection: "column",
  },
  smallTexts: {
    fontSize: 12,
    color: "gray",
  },

  menuWrapperView: {
    padding: 3,
    alignItems: "center",
    width: "10%",
  },
});
