import { StyleSheet, Text, View, Image, Pressable } from "react-native";
import React from "react";
import UploadsWrapper from "./UploadsWrapper";

const ProfilePage = () => {
  return (
    <View style={styles.container}>
      <View style={styles.wrapper}>
        <View style={styles.coverImgView}>
          {/* <Image /> */}
          <Text>This is image for Cover Img</Text>
        </View>
        <View style={styles.horizontalProfileInfo}>
          <View>
            {/* <Image /> */}
            <Text>PImg</Text>
          </View>
          <View style={styles.textsWrapper}>
            <View style={styles.channelNameAndUsername}>
              <Text style={styles.channelName}>Eric Bidopa</Text>
              <Text style={styles.channelUsername}>@KanyeWest</Text>
            </View>
            <View>
              <Text style={styles.numberOfSubscribersText}>
                10M Subscribers
              </Text>
            </View>
            <View>
              <Text>
                Provided to YouTube by Vydia Revelations 19:1 · Sunday Service
                Choir Jesus Is Born ℗ 2019 INC Released on: 2019-12-25 Composer:
                Sunday Service Choir Auto-generated by
              </Text>
            </View>
            <View></View>
          </View>
        </View>
        <View style={styles.buttonsWrapper}>
          <Text>Uploads</Text>
          <Pressable style={styles.buttons}>
            <Text>Settings</Text>
          </Pressable>
          <Pressable style={styles.buttons}>
            <Text>Upload</Text>
          </Pressable>
        </View>
        <UploadsWrapper />
      </View>
    </View>
  );
};

export default ProfilePage;

const styles = StyleSheet.create({

});
