import { StyleSheet, Text, View, Image, Pressable } from "react-native";
import React from "react";
import UploadsWrapper from "./UploadsWrapper";
import KanyeImg from "../assets/KanyeCoverArt.jpg";
import { Ionicons } from "@expo/vector-icons";

const ProfilePage = () => {
  return (
    <View style={styles.container}>
      <View style={styles.wrapper}>
        <View style={styles.coverImgView}>
          <Image style={styles.coverImageStyling} source={KanyeImg} />
        </View>
        <View style={styles.horizontalProfileInfo}>
          <View style={styles.profileImgView}>
            <Image style={styles.profileImgeStyling} source={KanyeImg} />
          </View>
          <View style={styles.textsWrapperView}>
            <View style={styles.channelNameAndUsername}>
              <Text style={styles.channelName}>Eric Bidopa</Text>
              <Text  style={styles.smallTexts}>@KanyeWest</Text>
            </View>
            <View>
              <Text  style={styles.smallTexts}>
                10M Subscribers
              </Text>
            </View>
            <View>
              <Text
                 style={styles.smallTexts}
                numberOfLines={3}
                ellipsizeMode="tail"
              >
                Provided to YouTube by Vydia Revelations 19:1 ·
                Choi Jesus More ℗ 2019 INC Released on: 2019-12-25 Composer More:
                Sunday Service Choir Auto-generated by
              </Text>
            </View>
          </View>
          <View style={styles.menuWrapperView}>
            <Ionicons name="options" size={25} color="black" />
          </View>
        </View>
        <View style={styles.buttonsWrapper}>
          <Text>Uploads</Text>
          <Pressable style={styles.buttons}>
            <Text>Settings</Text>
          </Pressable>
          <Pressable style={styles.buttons}>
            <Text>Upload</Text>
          </Pressable>
        </View>
        <UploadsWrapper />
      </View>
    </View>
  );
};

export default ProfilePage;

const styles = StyleSheet.create({
  container: {
    paddingHorizontal: 10,
    flex: 1,
  },
  wrapper: {
    flexDirection: "column",
    flex: 1,
    gap: 10,
    backgroundColor: "pink",
  },
  coverImgView: {
    backgroundColor: "blue",
    width: "100%",
    height: "15%",
  },
  coverImageStyling: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    borderRadius: 10,
  },

  horizontalProfileInfo: {
    flexDirection: "row",
    backgroundColor: "yellow",
    width: "100%",
    height: 130, // Set a specific height for the item
    marginBottom: 10,
  },
  profileImgView: {
    backgroundColor: "lightblue",
    width: 66, // Set the size of the image wrapper
    height: 66, // Set the size of the image wrapper
    overflow: "hidden",
  },
  profileImgeStyling: {
    width: "100%",
    height: "100%",
    borderRadius: 33,
  },

  textsWrapperView: {
    backgroundColor: "orange",
    flex: 1,
    paddingLeft: 10,
    justifyContent: "space-between",
    flexDirection: "column",
  },
  smallTexts: {
    fontSize: 12,
    color: "gray",
  },

  menuWrapperView: {
    padding: 3,
    alignItems: "center",
    width: "10%",
  },
  buttonsWrapper:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'lightpink',
    paddingHorizontal: '7%',
    alignItems: 'center'
  },
  buttons: {
    padding: 3,
    borderColor: "black",
    borderWidth: 0.5,
    alignItems: "center",
    borderRadius: 5,
    marginVertical: 5,
  },
});
